apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: talos-data
  namespace: poc-talos
  labels:
    app: talos
    autopoc.io/project: talos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
