apiVersion: v1
kind: Secret
metadata:
  name: talos-secrets
  namespace: poc-talos
  labels:
    app: talos
    autopoc.io/project: talos
type: Opaque
stringData:
  SECRETS_HMAC_CURRENT: "autopoc-hmac-secret-key-minimum-32-characters-long-for-security"
