apiVersion: v1
kind: Service
metadata:
  name: talos
  namespace: poc-talos
  labels:
    app: talos
    autopoc.io/project: talos
spec:
  type: ClusterIP
  selector:
    app: talos
  ports:
    - name: api
      port: 4420
      targetPort: 4420
      protocol: TCP
    - name: metrics
      port: 4422
      targetPort: 4422
      protocol: TCP
